### PR TITLE
Gilded Mall in Java

### PR DESCRIPTION
**Pull request by georgberky**
Hi Chris,

I found your OCP Kata via the Software Craftsmanship Slack and thought I'd port it to Java so we can have many languages to demonstrate the principle with.

Feel free to pull and merge if you like it.

Have a great day 😃,

Georg

### CODE REVIEW

**Comment by chrisfcarroll** [comment]
Thanks Georg! 
The more I think about it, the more tricky OCP seems to me. It potentially applies as a top-level architecture principle; applying it on a smaller and smaller scale is, I think, hard.

**Comment by georgberky** [comment]
You're very welcome! 

I used to find OCP hard to understand because it sounded very absolute. Everything seemed like it had to be open but closed at the same time. After some time I read the articles again and it turned out that it's the designer's choice where to apply closure for modification (and openness for extension) through abstraction. Nothing can be completely closed, after all.

When I tried your kata, I also realized that all of the other SOLID principles were involved. If we constantly extended existing code, we violate SRP at the level of abstraction of the extension point. We also need to make sure LSP is not violated if we choose subclassing as our extension strategy. When we build the extension mechanism, we observe DIP because the extension point is at the same (high) level of abstraction as the code that gets extended.

What you said about applying OCP at different levels is interesting! I will probably be thinking about this for some time, so I really appreciate the food-for-thought 😃. 

Here are some of my initial thoughts: It seems logical to me that we should be able to swap in and out the implementations of our stores from database to file system to in-memory. That's a pretty high level of abstraction already. 

Once we step into those layers themselves, it gets more complicated. It can be very cumbersome to make lower-level code extensible, so I tend to only do it when I have a reason (i.e. a requirement). I have seen too many examples of YAGNI pre-mature extensibility that nobody is able to understand anymore after a few weeks. 

So for the time being the refactoring path from code observing YAGNI to code observing OCP when it's time for extension seems to be at the heart of the kata for me right now.

Is microservices architecture an instance of OCP on a system components level for you?

Hope I didn't flood you with my thoughts too much...

**Comment by chrisfcarroll** [comment]
Your comments about use of extension points is an excellent point. Once you've said it, it seems obvious that implementing OCP means "identify your extension points".

Microservices: hmm. If I stay with your point about extensibility points, then I'd say "maybe". The thing is that 'microservice' means (I would say) "independently deployable component" and I think of OCP as applying to the "component" bit of that and not related to the "deployable" bit.

Relatedly, I've heard the idea of achieving a kind of OCP in an event/message driven architecture by writing event handlers which are sufficiently small that you never modify them, you only throw them away and replace them. The business process is open for extension (write new event handlers) but each code unit is closed for modification. Is that the same thing?

Perhaps OCP is complicated and should be refactoring into 2 principles! Maybe not. Perhaps the Single Responsibility of the principle is : to draw a clear line between how your is system is modifiable/extensible and where it isn't.

**Comment by georgberky** [comment]
Yes, being able to deploy independently doesn't seem to be the primary concern of OCP. Nevertheless, we do have to choose whether we want to add extensions by e.g. adding a new event handler (extension over the network) or by dropping another artifact into our application container (extension by calling code directly) where the already running application can pick up the new handler implementations and use them.

It will probably come down to the environment in which you want to use the extension. Network security could be a good reason to use the event handler approach because the connection will be initiated from the network segment of the extension whereas when you use the archive-drop-in-approach it will originate from the network segment of the extended application's container.

**Pull request merged**
